"""update_logs_table

Revision ID: 39671fe540fb
Revises: 98b05b8efd76
Create Date: 2026-07-14 11:46:15.629863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39671fe540fb'
down_revision: Union[str, Sequence[str], None] = '98b05b8efd76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_logs', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('interaction_logs', 'interaction_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interaction_logs', 'attendees',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('interaction_logs', 'materials_shared',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('interaction_logs', 'samples_distributed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('interaction_logs', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interaction_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('interaction_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_interaction_logs_hcp_name'), table_name='interaction_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_interaction_logs_hcp_name'), 'interaction_logs', ['hcp_name'], unique=False)
    op.alter_column('interaction_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('interaction_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('interaction_logs', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interaction_logs', 'samples_distributed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('interaction_logs', 'materials_shared',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('interaction_logs', 'attendees',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('interaction_logs', 'interaction_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('interaction_logs', 'updated_at')
    # ### end Alembic commands ###
