"""sentiment_nullable

Revision ID: 8daa132a9a5a
Revises: 39671fe540fb
Create Date: 2026-07-14 12:10:45.664474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8daa132a9a5a'
down_revision: Union[str, Sequence[str], None] = '39671fe540fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interaction_logs', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interaction_logs', 'sentiment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
