"""create_logs_table

Revision ID: 98b05b8efd76
Revises: 
Create Date: 2026-07-14 08:38:32.905445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98b05b8efd76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hcp_name', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('attendees', sa.JSON(), nullable=True),
    sa.Column('topics_discussed', sa.String(), nullable=True),
    sa.Column('materials_shared', sa.JSON(), nullable=True),
    sa.Column('samples_distributed', sa.JSON(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('outcomes', sa.String(), nullable=True),
    sa.Column('follow_up_actions', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_logs_hcp_name'), 'interaction_logs', ['hcp_name'], unique=False)
    op.create_index(op.f('ix_interaction_logs_id'), 'interaction_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_logs_id'), table_name='interaction_logs')
    op.drop_index(op.f('ix_interaction_logs_hcp_name'), table_name='interaction_logs')
    op.drop_table('interaction_logs')
    # ### end Alembic commands ###
